"""initial_schema

Revision ID: 27c3c2971c94
Revises: 
Create Date: 2026-08-08 23:49:50.158697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c3c2971c94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('person', 'organization', 'vehicle', 'phone', 'location', 'financial_account', name='entitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'under_investigation', 'cleared', name='entitystatus'), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_name'), ['name'], unique=False)
        batch_op.create_index('ix_entities_risk_score', ['risk_score'], unique=False)
        batch_op.create_index('ix_entities_type_status', ['entity_type', 'status'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('seizure', 'sighting', 'transaction', 'communication', 'border_crossing', 'meeting', 'tip', 'arrest', name='eventtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_events_location', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('ix_events_occurred', ['occurred_at'], unique=False)
        batch_op.create_index('ix_events_severity', ['severity'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', 'archived', name='investigationstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority'), nullable=False),
    sa.Column('lead_analyst', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index('ix_investigations_priority', ['priority'], unique=False)
        batch_op.create_index('ix_investigations_status', ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.Enum('anomaly', 'threshold', 'pattern', 'new_entity', 'risk_change', name='alerttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index('ix_alerts_created', ['created_at'], unique=False)
        batch_op.create_index('ix_alerts_is_read', ['is_read'], unique=False)
        batch_op.create_index('ix_alerts_severity', ['severity'], unique=False)

    op.create_table('event_entity',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'entity_id')
    )
    op.create_table('investigation_entity',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'entity_id')
    )
    op.create_table('investigation_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.Enum('associate', 'family', 'financial', 'communication', 'logistics', 'command', name='relationshiptype'), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('first_observed', sa.DateTime(), nullable=True),
    sa.Column('last_observed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index('ix_relationships_source', ['source_entity_id'], unique=False)
        batch_op.create_index('ix_relationships_target', ['target_entity_id'], unique=False)
        batch_op.create_index('ix_relationships_type', ['relationship_type'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('daily_brief', 'entity_profile', 'network_analysis', 'investigation_summary', name='reporttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index('ix_reports_created')

    op.drop_table('reports')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_relationships_type')
        batch_op.drop_index('ix_relationships_target')
        batch_op.drop_index('ix_relationships_source')

    op.drop_table('relationships')
    op.drop_table('investigation_notes')
    op.drop_table('investigation_entity')
    op.drop_table('event_entity')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_severity')
        batch_op.drop_index('ix_alerts_is_read')
        batch_op.drop_index('ix_alerts_created')
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index('ix_investigations_status')
        batch_op.drop_index('ix_investigations_priority')

    op.drop_table('investigations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_severity')
        batch_op.drop_index('ix_events_occurred')
        batch_op.drop_index('ix_events_location')
        batch_op.drop_index(batch_op.f('ix_events_event_type'))

    op.drop_table('events')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_type_status')
        batch_op.drop_index('ix_entities_risk_score')
        batch_op.drop_index(batch_op.f('ix_entities_name'))
        batch_op.drop_index(batch_op.f('ix_entities_entity_type'))

    op.drop_table('entities')
    # ### end Alembic commands ###
